# Generated by Django 3.2.7 on 2023-03-20 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20230320_1600'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
