# Generated by Django 3.2.7 on 2023-03-22 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_userprofile_delete_followerscount_delete_likepost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='relationship_status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
